apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://kubernetes-sigs.github.io/external-dns"
    chart: external-dns
    targetRevision: "1.15.0"
    helm:
      releaseName: external-dns
      valuesObject:
        serviceAccount:
          name: external-dns
          create: false
        txtOwnerId: Z045362311HFM5EEEZ1MH
        env:
          - name: AWS_DEFAULT_REGION
            value: ${region}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true