apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
 name: vCluster-Demo
 region: eu-central-1
nodeGroups:
 - name: ng-1
   instanceType: t3.medium
   desiredCapacity: 2
   volumeSize: 80

addons:
- name: aws-ebs-csi-driver
  wellKnownPolicies:      # this setting adds IAM and service account
    ebsCSIController: true