# node-provider.yaml
apiVersion: management.loft.sh/v1
kind: NodeProvider
metadata:
  name: gcp-compute
spec:
  terraform:
    nodeEnvironmentTemplate:
      infrastructure:
        git:
          repository: https://github.com/Liquid-Reply/vCluster-Demo.git
          branch: demo-auto-nodes
          subPath: auto-nodes/template/infrastructure
      kubernetes:
        git:
          repository: https://github.com/loft-sh/vcluster-auto-nodes-gcp.git
          tag: v0.1.0
          subPath: environment/kubernetes
    nodeTemplate:
      git:
        repository: https://github.com/Liquid-Reply/vCluster-Demo.git
        branch: demo-auto-nodes
        subPath: auto-nodes/template/node
    nodeTypes:
      # CPU node for general workloads
      - name: e2-small-europe-west1-b
        resources:
          cpu: "2"
          memory: "2Gi"
        properties:
          instance-type: e2-small
          region: europe-west1
          zone: europe-west1-b
          project: "*"
          accelerator: none
      
      # GPU node: N1-standard-1 + 1x T4 (your test config)
      - name: n1-standard-1-t4-europe-west1-b
        resources:
          cpu: "1"
          memory: "3.75Gi"
          nvidia.com/gpu: "1"
        properties:
          instance-type: n1-standard-1
          region: europe-west1
          zone: europe-west1-b
          project: "*"
          accelerator: nvidia-tesla-t4
          accelerator-count: "1"